const UPLOAD_DIR = "uploads";
const BODY_SIZE_LIMIT = "40mb";
const MAX_ATTACHMENT_COUNT = 5;
const MAX_UPLOAD_SIZE_BYTES = 5 * 1024 * 1024; // 5MB
const ORPHAN_UPLOAD_TTL_MS = 15 * 60 * 1000; // 15 minutes
const ORPHAN_CLEANUP_INTERVAL_MS = 60 * 1000; // 1 minute

export {
  BODY_SIZE_LIMIT,
  MAX_ATTACHMENT_COUNT,
  MAX_UPLOAD_SIZE_BYTES,
  ORPHAN_CLEANUP_INTERVAL_MS,
  ORPHAN_UPLOAD_TTL_MS,
  UPLOAD_DIR,
};
